---
services:
  db:
    image: mysql:5.7
    volumes:
    - db_data:/var/lib/mysql
    restart: always
    env_file:
    - .env
    
  web:
    depends_on:
    - db
    build:
      context: .
    env_file:
    - .env
    volumes:
    - .:/var/www/html
    ports:
    - "80:80"
    restart: always

volumes:
  db_data: {}
