---
services:
  db:
    image: mariadb:12.3@sha256:759869cb6f003234a95c6384cdee245b4bce7de26913fe607a8110362c0c007d
    volumes:
    - db_data:/var/lib/mysql
    env_file:
    - .env
    
  web:
    depends_on:
    - db
    build:
      context: .
      target: development
    env_file:
    - .env
    volumes:
    - ./docker/web/auth_openidc.conf:/etc/apache2/mods-enabled/auth_openidc.conf
    - ./docker/web/000-default.conf:/etc/apache2/sites-available/000-default.conf
    - .:/var/www/html
    ports:
    - "80:80"

volumes:
  db_data: {}
