---
services:
  db:
    image: mariadb:11.5
    volumes:
    - db_data:/var/lib/mysql
    env_file:
    - .env
    
  web:
    depends_on:
    - db
    build:
      context: .
    env_file:
    - .env
    volumes:
    - .:/var/www/html
    ports:
    - "80:80"

volumes:
  db_data: {}
