---
services:
  db:
    image: mariadb:13.0@sha256:d4fdec0510ad498e4f3127da30a99df3745bd6d5e611ae6ac5f76403d9284a8d
    volumes:
    - db_data:/var/lib/mysql
    env_file:
    - .env
    
  web:
    depends_on:
    - db
    build:
      context: .
      target: development
    env_file:
    - .env
    volumes:
    - ./docker/web/auth_openidc.conf:/etc/apache2/mods-enabled/auth_openidc.conf
    - ./docker/web/000-default.conf:/etc/apache2/sites-available/000-default.conf
    - .:/var/www/html
    ports:
    - "80:80"

volumes:
  db_data: {}
