---
services:
  db:
    build:
      context: .
      dockerfile: Dockerfile.db
      args:
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    env_file:
      - .env
    
  web:
    depends_on:
      - db
    build:
      context: .
    env_file:
      - .env
    volumes:
      - .:/var/www/html
    ports:
      - "80:80"
    restart: always

volumes:
  db_data: {}
