FROM php:5.6-apache

ARG APACHE_DOCUMENT_ROOT
ARG DOCKER_UID
ARG DOCKER_GID
ARG UNAME=app

RUN apt-get update && \
    apt-get install -y less && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN docker-php-ext-install pdo_mysql mysqli

RUN mkdir -p $(dirname ${APACHE_DOCUMENT_ROOT})

#Create the group for the user
RUN if [ x"${DOCKER_GID}" != x"" ] ; \
    then groupadd ${UNAME} -g ${DOCKER_GID} -o ; \
    else groupadd ${UNAME} ; \
    fi

#Create the User and assign ${APACHE_DOCUMENT_ROOT} as its home directory
RUN if [ x"${DOCKER_UID}" != x"" ] ; \
    then  useradd -m -d ${APACHE_DOCUMENT_ROOT} -u ${DOCKER_UID} -o -g ${UNAME} -s /bin/bash ${UNAME} ; \
    else useradd -m -d ${APACHE_DOCUMENT_ROOT} -g ${UNAME} -s /bin/bash ${UNAME} ; \
    fi

RUN curl https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar \
      > /usr/bin/wp && \
    chmod +x /usr/bin/wp

WORKDIR ${APACHE_DOCUMENT_ROOT}

RUN sed -ri -e 's!/var/www/html!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/sites-available/*.conf  && \
    sed -ri -e 's!/var/www/!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/apache2.conf /etc/apache2/conf-available/*.conf

COPY docker/web/000-default.conf /etc/apache2/sites-available/000-default.conf

RUN a2enmod rewrite ldap authnz_ldap

USER ${UNAME}

